[build]
  # Build command (not needed for static site)
  command = "echo 'Static site - no build required'"
  # Directory to publish
  publish = "."

[functions]
  # Directory containing Netlify Functions
  directory = "netlify/functions"
  # Use esbuild bundler for better ES module support
  node_bundler = "esbuild"

# Enable Netlify Blobs and set Node version
[build.environment]
  # Force Node.js 18+ which has better ES module support
  NODE_VERSION = "18"
  # Netlify Blobs is automatically available in functions

# Headers for security and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# API routes go to the function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Everything else goes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
