# netlify.toml - Fixed configuration
[build]
  publish = "."
  command = "npm install"
  
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs", "bcryptjs", "jsonwebtoken"]
  included_files = ["**/*.mjs", "**/*.js"]

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; img-src 'self' data: https:; connect-src 'self' https:; font-src 'self' https://cdnjs.cloudflare.com; media-src 'self' https:; frame-src 'self' https://www.youtube.com https://www.dailymotion.com; object-src 'none'; base-uri 'self'; form-action 'self';"

# API endpoints
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-cache"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-API-Key"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Path = "!/.netlify/functions/*"}

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/chat-api/*"
  to = "/.netlify/functions/chat-api/:splat"
  status = 200

# Disable secrets scanning for this project
[build.environment]
  SECRETS_SCAN_ENABLED = "false"

# Environment settings
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "preview"

[context.branch-deploy.environment]
  NODE_ENV = "development"
